### PR TITLE
Saving forever fix and opacity tooltip fixed

### LINKED ISSUE #7: LF or AL changes seem to save forever
refreshing the site shows that the data was saved to the backend but the saving animation (and run disable) stays until a manual refresh was used

### PR DESCRIPTION
**Pull request by lumburovskalina**
Fixed saving on labeling function and active learning pages from loading forever.
Opacity on button Run + weakly supervised fixed.

### CODE REVIEW

File: src/app/weak-supervision/components/weak-source-details/weak-source-details.component.ts [hunk 1]
```diff
@@ -424,7 +424,7 @@ export class WeakSourceDetailsComponent
           this.description,
           functionName
         ).pipe(first())
-        .subscribe();
+        .subscribe(() => this.informationSourceQuery$.refetch());
```
Comment (JWittmeyer) [inline src/app/weak-supervision/components/weak-source-details/weak-source-details.component.ts]: shouldn't be necessary because of the websockets (or at least that's the theory, ill double check)

Comment (JWittmeyer) [reply src/app/weak-supervision/components/weak-source-details/weak-source-details.component.ts]: it was only updated for different user ids (don't know why though).

Also refetching by hand on mutations isn't a common approach, usually, we would use refetch queries in apollo (however it's already there so no clue why it didn't work).

Can be resolved.

**Review by JWittmeyer — APPROVED** [review]
